# -*- coding: utf-8 -*-
"""Shared data for the Green Solar Energy site generator."""

SITE = {
    "name": "Green Solar Energy",
    "tagline": "Turning Sunlight into Savings",
    "email": "Greenenergy51@gmail.com",
    "phone_raw": "7441176223",
    "phone_disp": "+91 74411 76223",
    "phone_tel": "+917441176223",
    "wa": "https://wa.me/917441176223",
    "address": "Jaora, Madhya Pradesh",
    "address_full": "Jaora, District Ratlam, Madhya Pradesh 457226, India",
    "hours": "Mon – Sat : 9:00 AM – 7:00 PM",
    # Live domain used for the sitemap and canonical/OG URLs.
    # Update this the day a custom domain goes live.
    "domain": "https://green-energy-zeta-self.vercel.app",
}

M = "media/"

SERVICES = [
    {
        "slug": "residential-rooftop-solar",
        "title": "Residential Rooftop Solar",
        "short": "Complete 1kW–10kW rooftop solar systems for homes in Jaora and across Madhya Pradesh — cut your electricity bill to almost zero.",
        "icon": "fa-house-chimney",
        "badge": "Homes",
        "imgs": ["residential-rooftop-solar-1.jpg", "residential-rooftop-solar-2.avif", "residential-rooftop-solar-3.jpg"],
        "intro": [
            "A residential rooftop solar plant is the fastest way for a family in Jaora to stop paying rising MPMKVVCL electricity bills. Green Solar Energy designs, supplies and installs complete on-grid, off-grid and hybrid rooftop systems from 1kW to 10kW using DCR mono PERC modules, BIS-approved inverters and galvanised mounting structures built for Malwa region wind loads.",
            "Every home survey starts with your last 6 electricity bills. We size the plant against your real consumption, show you the exact monthly saving, and handle the DISCOM net-metering file and PM Surya Ghar subsidy application from start to finish.",
        ],
        "features": [
            ("Free Rooftop Survey", "Shadow analysis, roof strength check and load study done at your home at no cost."),
            ("Net-Metering Handled", "Complete DISCOM paperwork, feasibility and meter installation coordinated by our team."),
            ("Subsidy Assistance", "Up to ₹78,000 central subsidy under PM Surya Ghar credited directly to your bank account."),
            ("25 Year Performance", "Tier-1 modules with 25-year linear performance warranty and 5-year system warranty."),
        ],
        "benefits": [
            "Electricity bill reduced by 80–100% from the first billing cycle",
            "System pays for itself in roughly 3 to 4 years",
            "Zero export charges — surplus units banked with the DISCOM",
            "Adds long-term value to your property",
            "Silent operation with no fuel, no smoke and near-zero running cost",
            "Free of cost annual health check for the first two years",
        ],
        "faqs": [
            ("How much roof area is needed for a 3kW home system?", "About 250–300 sq. ft. of shadow-free roof is enough for a 3kW system. We confirm the exact layout during the free site survey."),
            ("Will solar work during a power cut?", "A standard on-grid system shuts down during a cut for safety. If you need backup, we recommend a hybrid system with battery — we install both."),
        ],
    },
    {
        "slug": "commercial-solar-solutions",
        "title": "Commercial Solar Solutions",
        "short": "Rooftop and ground-mounted solar for shops, showrooms, schools, hospitals and offices — lower operating cost, faster payback.",
        "icon": "fa-building",
        "badge": "Business",
        "imgs": ["commercial-solar-solutions-1.jpg", "commercial-solar-solutions-2.webp", "commercial-solar-solutions-3.jpg"],
        "intro": [
            "Commercial tariffs in Madhya Pradesh are among the highest slabs a business pays. A correctly sized commercial solar plant converts that recurring expense into a depreciating asset with a 3–5 year payback and 25 years of near-free generation.",
            "Green Solar Energy handles commercial projects from 5kW to 500kW — schools, hospitals, hotels, petrol pumps, showrooms, cold storages and office buildings — including structure design, HT/LT coordination, net metering and accelerated depreciation documentation for your accountant.",
        ],
        "features": [
            ("Load & Tariff Study", "We analyse your sanctioned load, tariff slab and demand charges before proposing a system size."),
            ("Accelerated Depreciation", "40% accelerated depreciation benefit documented for your CA to claim in the first year."),
            ("Remote Monitoring", "Live generation dashboard on mobile with alerts for underperformance."),
            ("Minimal Downtime", "Installation planned around your business hours so operations never stop."),
        ],
        "benefits": [
            "30–60% cut in monthly operating electricity cost",
            "Protection from annual tariff hikes for 25 years",
            "Accelerated depreciation and tax benefits for registered businesses",
            "Strong green credentials for your brand and CSR reporting",
            "Scalable design — add capacity as your load grows",
            "Annual maintenance contracts with guaranteed response time",
        ],
        "faqs": [
            ("What is the payback period for a commercial plant?", "For most commercial connections in Madhya Pradesh the payback works out to 3 to 5 years, depending on your tariff slab and daytime consumption pattern."),
            ("Can I install solar on a rented building?", "Yes. We install on leased premises with a landlord NOC, and the structure can be designed to be relocatable."),
        ],
    },
    {
        "slug": "industrial-solar-power-systems",
        "title": "Industrial Solar Power Systems",
        "short": "High-capacity solar plants for factories, mills, cold storages and processing units with HT net metering and 24×7 monitoring.",
        "icon": "fa-industry",
        "badge": "Industry",
        "imgs": ["industrial-solar-power-systems-1.jpg", "industrial-solar-power-systems-2.webp", "industrial-solar-power-systems-3.webp", "industrial-solar-power-systems-4.jpg"],
        "intro": [
            "Industrial units in the Ratlam–Jaora–Mandsaur belt run heavy daytime loads — exactly the profile where solar delivers the highest return. Green Solar Energy engineers industrial plants from 100kW to multi-MW on rooftops, sheds and adjoining land.",
            "Our scope covers structural engineering for large sheds, string design, SCADA-ready monitoring, LT/HT panel integration, earthing and lightning protection, safety compliance and complete liaison with the DISCOM for HT net metering approval.",
        ],
        "features": [
            ("Engineered Structures", "Wind-load certified mounting for sheds, trusses and open land with soil testing where required."),
            ("SCADA Monitoring", "String-level monitoring with generation reports and downtime alerts."),
            ("Safety Compliance", "Earthing, surge protection, fire safety clearance and electrical inspectorate approval."),
            ("O&M Contracts", "Scheduled cleaning, thermography and preventive maintenance packages."),
        ],
        "benefits": [
            "Large reduction in per-unit power cost for high-consumption units",
            "Hedge against demand charges and future tariff revisions",
            "Meets renewable purchase obligation and ESG reporting needs",
            "Robust structures designed for 25+ year service life",
            "String-level fault detection to protect generation",
            "Complete statutory liaison handled by our project team",
        ],
        "faqs": [
            ("Do you handle HT net metering approvals?", "Yes. Our team prepares the complete technical file, single line diagram and liaises with the DISCOM until the HT net meter is commissioned."),
            ("Can solar run heavy machinery directly?", "Yes — with correctly sized inverters and, where the load profile demands it, a hybrid configuration with battery support."),
        ],
    },
    {
        "slug": "solar-panel-installation",
        "title": "Solar Panel Installation",
        "short": "Certified installation crews, galvanised structures and clean cable management — installed right the first time.",
        "icon": "fa-screwdriver-wrench",
        "badge": "Installation",
        "imgs": ["solar-panel-installation-1.jpg", "solar-panel-installation-4.jpg"],
        "intro": [
            "A solar plant performs only as well as the hands that installed it. Green Solar Energy uses in-house trained crews — not casual labour — with the correct torque tools, DC-rated connectors, UV-grade cables and proper roof waterproofing.",
            "We install on RCC roofs, tin sheds, tiled roofs, elevated structures and open ground. Every installation ends with a commissioning report, string test readings, earthing values and a walkthrough of your monitoring app.",
        ],
        "features": [
            ("Trained In-House Crew", "Certified installers who follow a documented 42-point installation checklist."),
            ("Galvanised Structure", "Hot-dip galvanised or high-grade GI structures rated for local wind speeds."),
            ("Waterproof Mounting", "Roof penetrations sealed and treated so your terrace never leaks."),
            ("Commissioning Report", "String voltages, earth resistance and inverter settings documented and handed over."),
        ],
        "benefits": [
            "Typical residential installation completed in 2–4 days",
            "Correct tilt and azimuth for maximum yearly generation",
            "Neat, UV-protected DC/AC cable routing in conduits",
            "Proper earthing and lightning arrestor for safety",
            "Post-installation walkthrough and app training",
            "Free workmanship warranty for 5 years",
        ],
        "faqs": [
            ("How long does installation take?", "A 3kW–5kW residential system takes 2 to 4 working days after material delivery. Larger commercial plants are scheduled with a written timeline."),
            ("Will drilling damage my roof?", "No. All penetrations are sealed with grade-A waterproof compound, and on many roofs we use ballast-based structures with no drilling at all."),
        ],
    },
    {
        "slug": "solar-inverter-battery-solutions",
        "title": "Solar Inverter & Battery Solutions",
        "short": "On-grid, off-grid and hybrid inverters with lithium or tubular battery banks sized for real backup, not guesswork.",
        "icon": "fa-car-battery",
        "badge": "Power Backup",
        "imgs": ["solar-inverter-battery-solutions-1.webp", "solar-inverter-battery-solutions-4.webp"],
        "intro": [
            "The inverter is the brain of your solar plant and the battery decides how much of the night it can carry. We supply and install BIS-certified string inverters, hybrid inverters and MPPT charge controllers from established brands, matched to lithium (LFP) or tall-tubular battery banks.",
            "Backup sizing starts with an honest load list — fans, lights, fridge, TV, pump, ACs — so you get the runtime you actually need without paying for battery you will never use.",
        ],
        "features": [
            ("Right-Sized Backup", "Load audit first, battery bank sized to your real night-time requirement."),
            ("Lithium or Tubular", "LFP lithium for long life and zero maintenance, or tubular batteries for lower upfront cost."),
            ("MPPT Efficiency", "MPPT charge controllers that harvest 20–30% more than old PWM units."),
            ("Safe Installation", "Proper ventilation, fusing, DC isolators and battery racking as per standards."),
        ],
        "benefits": [
            "Uninterrupted power through DISCOM outages and load shedding",
            "Lithium options with 6000+ cycle life and 10-year warranty",
            "Wi-Fi enabled inverters with live app monitoring",
            "Battery bank expandable later without replacing the inverter",
            "Surge and short-circuit protection built in",
            "On-site service support across Ratlam district",
        ],
        "faqs": [
            ("Lithium or lead-acid — which should I choose?", "Lithium costs more upfront but lasts 3–4 times longer, needs no water topping and gives more usable capacity. For daily backup use it works out cheaper over the system life."),
            ("Can I add a battery to my existing on-grid system?", "Yes, by adding a hybrid inverter or a retrofit battery-ready unit. We survey the existing plant and give you a clear upgrade quote."),
        ],
    },
    {
        "slug": "solar-maintenance-support",
        "title": "Solar Maintenance & Support",
        "short": "AMC packages, panel cleaning, performance audits and fast breakdown response so your plant never underperforms.",
        "icon": "fa-gears",
        "badge": "AMC & Service",
        "imgs": ["solar-maintenance-support-2.webp", "solar-maintenance-support-3.webp"],
        "intro": [
            "Dust in the Malwa belt can cut solar generation by 15–25% within weeks. Regular cleaning, connection checks and inverter health monitoring are what keep a plant producing at its rated output for 25 years.",
            "Green Solar Energy offers annual maintenance contracts for systems of any size — including plants we did not install. Each visit is documented with before/after generation readings so you can see exactly what the service recovered.",
        ],
        "features": [
            ("Scheduled Cleaning", "Module cleaning cycles planned around the season and local dust conditions."),
            ("Performance Audit", "String testing, thermography and generation comparison against expected yield."),
            ("Fast Breakdown Support", "Priority response for AMC customers across Jaora, Ratlam and nearby towns."),
            ("Documented Reports", "Every visit closed with a signed service report and readings."),
        ],
        "benefits": [
            "Recovers 15–25% generation lost to dust and soiling",
            "Early detection of hot spots, loose DC joints and failing modules",
            "Inverter firmware and settings kept up to date",
            "Warranty claims filed and followed up on your behalf",
            "AMC for systems installed by any vendor",
            "Transparent yearly pricing with no hidden charges",
        ],
        "faqs": [
            ("How often should panels be cleaned?", "Every 15–30 days in dusty months and at least once a month otherwise. Our AMC schedules cleaning automatically so you don't have to track it."),
            ("Do you service systems installed by other companies?", "Yes. We take over third-party systems after a one-time health audit and then bring them onto a regular AMC schedule."),
        ],
    },
    {
        "slug": "solar-subsidy-assistance",
        "title": "Solar Subsidy Assistance",
        "short": "End-to-end PM Surya Ghar subsidy filing — registration, vendor selection, inspection and up to ₹78,000 credited to your account.",
        "icon": "fa-file-invoice-dollar",
        "badge": "Subsidy",
        "imgs": ["solar-subsidy-assistance-1.jpg", "solar-subsidy-assistance-2.avif", "solar-subsidy-assistance-3.jpeg", "solar-subsidy-assistance-4.jpg"],
        "intro": [
            "Most homeowners lose their subsidy not because they are ineligible, but because the portal application, DISCOM feasibility or inspection step gets stuck. Green Solar Energy is a registered vendor and files the entire PM Surya Ghar Muft Bijli Yojana application for you.",
            "From national portal registration to net-meter installation, DISCOM inspection and subsidy disbursal into your bank account — we track every stage and keep you updated at each step.",
        ],
        "features": [
            ("Portal Registration", "Consumer registration, vendor selection and application submitted correctly the first time."),
            ("Document Preparation", "Electricity bill, Aadhaar, bank details and roof ownership proof compiled and verified."),
            ("Inspection Coordination", "Net meter installation and DISCOM inspection scheduled and attended by our team."),
            ("Disbursal Follow-Up", "We follow the file until the subsidy is credited — typically within 30–45 days of commissioning."),
        ],
        "benefits": [
            "₹30,000 subsidy for a 1kW system",
            "₹60,000 subsidy for a 2kW system",
            "₹78,000 maximum central subsidy for 3kW and above",
            "Subsidy credited directly to your own bank account",
            "No agent commission, no hidden processing charges",
            "Full status visibility at every stage of the application",
        ],
        "faqs": [
            ("Who is eligible for the PM Surya Ghar subsidy?", "Any Indian household with a valid electricity connection, a suitable shadow-free roof and a bank account linked to Aadhaar. The subsidy applies to residential connections only."),
            ("How long does the subsidy take to arrive?", "Usually 30 to 45 days after commissioning and net-meter installation, provided documents are complete."),
        ],
    },
    {
        "slug": "energy-consultation",
        "title": "Energy Consultation",
        "short": "Independent load study, savings projection and system sizing so you invest in exactly the right capacity.",
        "icon": "fa-clipboard-check",
        "badge": "Consulting",
        "imgs": ["energy-consultation-2.avif", "energy-consultation-3.jpg"],
        "intro": [
            "Buying a solar plant that is too small wastes the opportunity; buying one that is too large wastes money. Our consultation service starts with data — your bills, your load pattern, your roof and your budget — and ends with a written recommendation you can compare against any other quote.",
            "You receive a clear document: recommended capacity, expected annual generation, projected savings, subsidy eligibility, payback period and a 25-year return estimate.",
        ],
        "features": [
            ("Bill & Load Analysis", "12 months of consumption analysed to find the right system size."),
            ("Shadow & Roof Study", "On-site shadow mapping and structural feasibility assessment."),
            ("Savings Projection", "Year-by-year savings and payback modelled on current tariffs."),
            ("Vendor-Neutral Advice", "Honest guidance on on-grid vs hybrid vs off-grid for your situation."),
        ],
        "benefits": [
            "Know your exact payback before you spend a rupee",
            "Avoid oversized systems and unnecessary battery cost",
            "Clear comparison of on-grid, off-grid and hybrid options",
            "Subsidy eligibility confirmed upfront",
            "Written report you can use to evaluate any quotation",
            "Free of cost for customers in and around Jaora",
        ],
        "faqs": [
            ("Is the consultation really free?", "Yes — the site survey, load study and savings report are free for homes and businesses in Jaora and the surrounding area."),
            ("Do I have to buy from you after the consultation?", "No. The report is yours to keep and compare. We are confident our pricing and service will speak for themselves."),
        ],
    },
    {
        "slug": "solar-water-heater",
        "title": "Solar Water Heater",
        "short": "ETC and FPC solar water heaters from 100 LPD to 5000 LPD for homes, hostels, hotels and dairies.",
        "icon": "fa-shower",
        "badge": "Hot Water",
        "imgs": ["solar-water-heater-1.png", "solar-water-heater-2.png", "solar-water-heater-3.png"],
        "intro": [
            "A solar water heater is the fastest-paying solar product you can buy — it removes the single largest winter load in most homes, the electric geyser. Green Solar Energy supplies BIS-approved ETC (evacuated tube) and FPC (flat plate) systems from 100 LPD for a family to 5000 LPD for hostels and hotels.",
            "Systems come with stainless steel inner tanks, PUF insulation for overnight heat retention, and an optional electric backup element for long cloudy spells.",
        ],
        "features": [
            ("ETC & FPC Options", "Evacuated tube for value and fast heating, flat plate for hard water and high pressure."),
            ("100–5000 LPD", "Domestic, hostel, hotel, hospital and dairy capacities available."),
            ("SS Inner Tank", "Food-grade stainless steel tank with thick PUF insulation for overnight hot water."),
            ("Backup Heater", "Optional electric element for cloudy days — automatic, no switching needed."),
        ],
        "benefits": [
            "Cuts geyser electricity consumption by up to 90%",
            "Payback in about 2 years for most households",
            "Hot water available early morning without waiting",
            "Zero running cost and almost no maintenance",
            "Pressurised models available for overhead shower systems",
            "5-year warranty on tank and collectors",
        ],
        "faqs": [
            ("Does a solar water heater work in winter?", "Yes. Evacuated tube collectors work well even in cold weather. On consecutive cloudy days the optional electric backup takes over automatically."),
            ("What capacity does my family need?", "Roughly 25 litres per person per day — a family of four is comfortable with a 100–150 LPD system."),
        ],
    },
    {
        "slug": "solar-water-pump",
        "title": "Solar Water Pump",
        "short": "PM-KUSUM eligible solar pumps from 1HP to 10HP — surface and submersible, AC and DC, for farms across Malwa.",
        "icon": "fa-faucet-drip",
        "badge": "Agriculture",
        "imgs": ["solar-water-pump-1.jpg", "solar-water-pump-2.jpg", "solar-water-pump-3.webp"],
        "intro": [
            "Diesel pumps cost money every hour they run and grid supply to farms is rarely available when the crop needs water. A solar water pump irrigates on sunlight, with zero fuel cost and no dependence on the feeder schedule.",
            "Green Solar Energy installs surface and submersible solar pumps from 1HP to 10HP with VFD controllers, dry-run protection and remote monitoring — and assists with PM-KUSUM scheme applications where applicable.",
        ],
        "features": [
            ("1HP to 10HP", "AC and DC, surface and submersible pump sets for borewells, open wells and canals."),
            ("VFD Controller", "Variable frequency drive with dry-run and overload protection built in."),
            ("KUSUM Assistance", "Documentation support for PM-KUSUM scheme benefits where eligible."),
            ("Tracking Structures", "Optional manual tracking structures to extend daily pumping hours."),
        ],
        "benefits": [
            "Zero diesel cost — irrigation runs entirely on sunlight",
            "Water available exactly when the crop needs it",
            "No dependence on farm feeder supply timings",
            "Low maintenance with no engine servicing",
            "Life of 20+ years for panels, 5+ years for the pump set",
            "Service support at your field, not just on the phone",
        ],
        "faqs": [
            ("How many hours will a solar pump run daily?", "Typically 6 to 8 hours of effective pumping on a clear day, depending on panel capacity, head and season."),
            ("Can it run at night or on cloudy days?", "A standard solar pump runs on live sunlight. For round-the-clock pumping we offer hybrid controllers that can switch to grid supply."),
        ],
    },
    {
        "slug": "solar-street-light",
        "title": "Solar Street Light",
        "short": "All-in-one and semi-integrated solar street lights from 9W to 200W for panchayats, colonies, farms and factories.",
        "icon": "fa-lightbulb",
        "badge": "Lighting",
        "imgs": ["solar-street-light-1.jpg", "solar-street-light-2.jpg", "solar-street-light-3.webp", "solar-street-light-4.jpg"],
        "intro": [
            "Solar street lights need no cable trenching, no meter and no monthly bill — which makes them ideal for village roads, farm approaches, colony lanes, factory perimeters and school campuses.",
            "We supply all-in-one integrated lights and semi-integrated systems with LiFePO4 batteries, dusk-to-dawn automatic operation, motion sensing and IP65/IP66 weatherproof housings, complete with GI poles and civil foundation.",
        ],
        "features": [
            ("9W to 200W", "Full range for lanes, main roads, campuses and industrial perimeters."),
            ("LiFePO4 Battery", "Long-life lithium batteries rated for 3–4 rainy days of autonomy."),
            ("Auto Dusk-to-Dawn", "Automatic on/off with motion sensing to conserve charge in low traffic hours."),
            ("Pole & Foundation", "GI poles, clamps and civil foundation included in the installation scope."),
        ],
        "benefits": [
            "No cabling, no electricity meter and no monthly bill",
            "Continues working during grid outages",
            "3–4 days of backup even in continuous cloudy weather",
            "IP65/IP66 housings built for monsoon and dust",
            "Ideal for panchayat, MLA/MP fund and CSR projects",
            "Bulk supply with installation across Madhya Pradesh",
        ],
        "faqs": [
            ("How long does a solar street light stay on?", "Dusk to dawn — typically 10 to 12 hours, with motion-sensing models running at reduced output when no movement is detected."),
            ("Do you supply in bulk for panchayats?", "Yes. We handle bulk orders with installation, GI poles, foundation work and documentation for government-funded projects."),
        ],
    },
    {
        "slug": "solar-hybrid-system",
        "title": "Solar Hybrid System",
        "short": "Grid + solar + battery in one intelligent system — bill savings during the day, guaranteed backup at night.",
        "icon": "fa-bolt",
        "badge": "Hybrid",
        "imgs": ["solar-hybrid-system-1.jpg", "solar-hybrid-system-2.jpg", "solar-hybrid-system-3.webp"],
        "intro": [
            "A hybrid system gives you both things people want from solar: a lower electricity bill and power that stays on when the grid goes off. The hybrid inverter runs your home on solar first, charges the battery next, and exports the surplus to the grid.",
            "When supply fails, the changeover is instant — your fans, lights, fridge and Wi-Fi never notice. Green Solar Energy designs hybrid systems from 3kW to 50kW for homes, clinics, shops and small industries where downtime is expensive.",
        ],
        "features": [
            ("Instant Changeover", "Sub-20ms transfer — connected equipment never restarts during an outage."),
            ("Smart Priority Logic", "Solar first, battery second, grid last — configured to your usage pattern."),
            ("Net Metering Ready", "Surplus generation exported and banked with the DISCOM."),
            ("App Monitoring", "Live solar, battery, load and grid data on your phone."),
        ],
        "benefits": [
            "Bill savings of an on-grid system plus the backup of an off-grid system",
            "Battery reserved intelligently for outage hours",
            "Works with lithium or tubular battery banks",
            "Expandable — add panels or batteries later",
            "Protects sensitive equipment from voltage fluctuation",
            "Ideal for clinics, shops, and work-from-home households",
        ],
        "faqs": [
            ("Is a hybrid system worth the extra cost?", "If your area sees frequent or long outages, yes. You avoid buying a separate inverter-battery setup, and the same battery earns its keep every day."),
            ("Can my existing on-grid system be converted to hybrid?", "In most cases yes, by replacing the inverter with a hybrid unit and adding a battery bank. We audit the existing plant first and give a fixed quote."),
        ],
    },
]

WHY_CHOOSE = [
    ("fa-award", "10+ Years of Field Experience", "A decade of designing, installing and servicing solar across the Malwa region — not a franchise, a local team you can visit."),
    ("fa-solar-panel", "Tier-1 Components Only", "DCR-compliant mono PERC modules, BIS-certified inverters and galvanised structures. No grey-market material, ever."),
    ("fa-file-invoice-dollar", "Full Subsidy Handling", "PM Surya Ghar registration, DISCOM feasibility, net metering and disbursal follow-up handled end to end."),
    ("fa-screwdriver-wrench", "In-House Installation Crew", "Trained, salaried installers working from a 42-point checklist — never outsourced daily-wage labour."),
    ("fa-headset", "Local Service, Fast Response", "Based in Jaora. Service calls in the district are attended quickly, not scheduled for next month."),
    ("fa-shield-check", "25-Year Performance Warranty", "Linear performance warranty on modules plus a written 5-year system and workmanship warranty."),
    ("fa-wallet", "Transparent Pricing", "Itemised quotations with brand and model names. What you sign is what you pay — no surprise extras."),
    ("fa-chart-line", "Real Savings, Measured", "We show you projected generation before you buy, and verified generation reports after commissioning."),
]

PROCESS = [
    ("fa-phone-volume", "Free Consultation", "Call or WhatsApp us. We review your electricity bills, understand your load and answer every question — no obligation."),
    ("fa-clipboard-check", "Site Survey & Design", "Our engineer visits your site for shadow analysis and roof study, then designs a system sized to your actual consumption."),
    ("fa-screwdriver-wrench", "Installation & Subsidy", "Structure, modules, inverter and wiring installed by our own crew while we file your subsidy and net-metering paperwork."),
    ("fa-gears", "Commissioning & Support", "Net meter installed, plant commissioned, app training given — followed by scheduled maintenance and lifetime support."),
]

TESTIMONIALS = [
    ("Rajesh Patidar", "Jaora, Ratlam", "Installed a 5kW rooftop system at my house in Jaora. Bill came down from ₹4,200 to under ₹300 in the very first month. The subsidy of ₹78,000 also came into my account without me visiting any office."),
    ("Sunita Sharma", "Ratlam City", "The team explained everything in simple language and did not push a bigger system than we needed. Installation was clean and the terrace has no leakage even after the monsoon."),
    ("Mahesh Chouhan", "Mandsaur", "We run a flour mill and our monthly bill was crossing ₹40,000. After the 25kW plant it is about ₹12,000. Payback is looking like three and a half years."),
    ("Dr. Anil Verma", "Neemuch", "Hybrid system for my clinic. Power cuts used to disturb patients daily — now nothing switches off. Best decision for the clinic."),
    ("Kailash Prajapat", "Alot, Ratlam", "Took a 5HP solar pump for my field. No diesel expense since installation and water is available whenever I need it, not only when the feeder gives supply."),
    ("Priya Jain", "Ujjain", "Solar water heater at home for two years now. The geyser has not been switched on even once in winter. Very satisfied with the service."),
    ("Ramesh Solanki", "Piploda", "Our panchayat ordered solar street lights. Installation with poles and foundation was completed on time and all lights are still working perfectly after eighteen months."),
    ("Vikram Singh Rathore", "Sailana", "I had quotations from three companies. Green Solar Energy gave the clearest breakup with brand names written on it. No hidden charges came later."),
    ("Nilesh Agrawal", "Nagda", "Commercial system for our showroom. They planned the work on a Sunday so the shop never closed. Monitoring app shows generation daily."),
    ("Sarita Bhabhor", "Badnawar, Dhar", "Service team came within a day when our inverter showed an error. Replaced it under warranty at no cost. That kind of support is rare."),
    ("Imran Khan", "Dewas", "Shifted our cold storage to a 60kW plant. Generation is even higher than what they projected in the report. Very professional handling.")
    ,
    ("Govind Malviya", "Shajapur", "Took the AMC package for a system installed by another company. After cleaning and repairs the generation went up by almost 20 units a day."),
]

FAQS_HOME = [
    ("How much can I actually save with rooftop solar in Madhya Pradesh?",
     "For a typical household in Jaora with a monthly bill of ₹3,000–₹5,000, a 3kW rooftop system usually brings the bill down to the minimum fixed charges — a saving of 80% to 100%. With the PM Surya Ghar subsidy of up to ₹78,000, most homes recover their entire investment within 3 to 4 years and then generate free power for the remaining 20+ years of system life."),
    ("How do I get the ₹78,000 PM Surya Ghar subsidy?",
     "The subsidy is credited directly to your bank account after your system is installed and the net meter is commissioned. You need a residential electricity connection, a shadow-free roof, Aadhaar and a bank account. Green Solar Energy is a registered vendor and files the entire application — portal registration, DISCOM feasibility, inspection and disbursal follow-up — on your behalf at no extra charge."),
    ("What is the difference between on-grid, off-grid and hybrid systems?",
     "An on-grid system works with the DISCOM supply and gives the maximum bill savings, but shuts down during a power cut. An off-grid system runs entirely on battery and is used where there is no reliable grid. A hybrid system does both — it saves on your bill during the day and keeps your home running on battery during outages. We recommend the right one after studying your load and outage pattern."),
    ("What maintenance does a solar system need, and what warranty do I get?",
     "Panels need cleaning every 15–30 days and an annual electrical health check — that is all. Modules carry a 25-year linear performance warranty, inverters typically 5–10 years, and Green Solar Energy adds a written 5-year system and workmanship warranty. We also offer AMC packages that include scheduled cleaning, performance audits and priority breakdown support."),
]

VIDEOS = [
    ("video-1.mp4", "Rooftop Installation in Progress"),
    ("video-2.mp4", "Commissioning a Home Solar Plant"),
    ("video-3.mp4", "Commercial Rooftop Project"),
    ("video-4.mp4", "Site Survey & Customer Handover"),
]

GALLERY = [
    ("residential-rooftop-solar-1.jpg", "Residential Rooftop Installation", "residential"),
    ("residential-rooftop-solar-2.avif", "Home Solar System, Jaora", "residential"),
    ("residential-rooftop-solar-3.jpg", "Rooftop Array on RCC Roof", "residential"),
    ("commercial-solar-solutions-1.jpg", "Commercial Rooftop Plant", "commercial"),
    ("commercial-solar-solutions-2.webp", "Showroom Solar Installation", "commercial"),
    ("commercial-solar-solutions-3.jpg", "Institutional Solar Project", "commercial"),
    ("industrial-solar-power-systems-1.jpg", "Industrial Shed Solar Plant", "industrial"),
    ("industrial-solar-power-systems-2.webp", "High Capacity Solar Array", "industrial"),
    ("industrial-solar-power-systems-3.webp", "Factory Rooftop System", "industrial"),
    ("industrial-solar-power-systems-4.jpg", "Ground Mounted Solar Plant", "industrial"),
    ("solar-panel-installation-1.jpg", "Module Mounting Work", "installation"),
    ("solar-panel-installation-4.jpg", "Structure & Panel Fixing", "installation"),
    ("solar-inverter-battery-solutions-1.webp", "Inverter & Battery Setup", "installation"),
    ("solar-inverter-battery-solutions-4.webp", "Hybrid Inverter Installation", "installation"),
    ("solar-maintenance-support-2.webp", "Panel Cleaning & Service", "installation"),
    ("solar-maintenance-support-3.webp", "Performance Audit Visit", "installation"),
    ("solar-subsidy-assistance-1.jpg", "Subsidy Documentation Support", "products"),
    ("solar-subsidy-assistance-3.jpeg", "PM Surya Ghar Assistance", "products"),
    ("solar-water-heater-1.png", "Solar Water Heater Installation", "products"),
    ("solar-water-heater-3.png", "ETC Water Heater System", "products"),
    ("solar-water-pump-1.jpg", "Solar Water Pump for Farms", "products"),
    ("solar-water-pump-2.jpg", "Submersible Solar Pump Set", "products"),
    ("solar-street-light-1.jpg", "Solar Street Light Installation", "products"),
    ("solar-street-light-4.jpg", "All-in-One Street Light", "products"),
    ("solar-hybrid-system-1.jpg", "Hybrid Solar System", "installation"),
    ("solar-hybrid-system-2.jpg", "Battery Bank Installation", "installation"),
    ("energy-consultation-3.jpg", "Customer Consultation", "commercial"),
    ("pmsg-2.webp", "PM Surya Ghar Beneficiary Site", "residential"),
]
